### PR TITLE
Fixed the screwed analog inputs in the xbox360usb module

### PR DESCRIPTION
**Pull request by RoloDeOvo**
## Pull Request checklist

Note: these are not necessarily requirements

- [ ] I reformatted the code with clang-format
- [x] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK
- [ ] Requires update of the gsKit
- [ ] Others (please specify below)

### CODE REVIEW

**Comment by belek666** [comment]
Thank you. It would be great if You add note about which device game was started from (usb, hdd, smb). I'm planing return to developing on pademu modules.

**Comment by RoloDeOvo** [comment]
Oh, hello! I started every game from an HDD. I'm gonna update the compatibility list to include devices as well.
By the way, should i move the compatibility list elsewhere or do i keep it in the master branch?

**Comment by belek666** [comment]
Separate branch would be better. Master need some updates :)

**Comment by RoloDeOvo** [comment]
Ok, i will move it to another branch. Sorry about that last commit.

**Pull request merged**
